[package]
name = "descriptor-wallet"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Library for building descriptor-based bitcoin wallets"
repository = "https://github.com/rust-bitcoin/descriptor-wallet"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "miniscript"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib", "slip132"]

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = { version = "3.7.1", features = ["stringly_conversions"] }
slip132 = { version = "0.3.4", path = "./slip132" }
commit_verify = "0.5.4"
strict_encoding = { version = "1.6.0", features = ["bitcoin", "miniscript", "derive"] } # TODO: Make strict encoding optional and decrease MSRV
bitcoin = "0.27"
miniscript = { version = "6", features = ["compiler"] }
electrum-client = { version = "0.8", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
lazy_static = "1.4"
regex = "1.4" # TODO: Remove dependency
chrono = "0.4"

[dev-dependencies]
bitcoin = { version = "0.26.2", features = ["rand"] }

[features]
default = []
all = ["keygen", "serde", "electrum"]
keygen = ["bitcoin/rand", "commit_verify/rand"]
electrum = ["electrum-client"]
serde = ["serde_crate", "serde_with", "amplify/serde",
         "bitcoin/use-serde", "miniscript/serde"]

[workspace]
members = [".", "slip132", "libbitcoin"]
default-members = ["."]
exclude = ["dep_test"]
