[package]
name = "descriptor-wallet"
version = "0.8.2"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Libraries and command line tool for building descriptor-based bitcoin wallets"
repository = "https://github.com/rust-bitcoin/descriptor-wallet"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "miniscript"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt"]

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "btc-hot"
required-features = ["hot", "cli"]

[[bin]]
name = "btc-cold"
required-features = ["electrum", "cli", "miniscript"]

[dependencies]
amplify = "3.12.1"
descriptors = { version = "0.8.0", path = "./descriptors", optional = true, default-features = false }
bitcoin_scripts = { version = "0.8.2", path = "./scripts" }
bitcoin_hd = { version = "0.8.1", path = "./hd" }
bitcoin_onchain = { version = "0.8.1", path = "./onchain" }
psbt = { version = "0.8.3", path = "./psbt", default-features = false }
slip132 = { version = "0.8.0", path = "./slip132", features = ["strict_encoding"] }
# TODO #5: Make strict encoding optional
strict_encoding = { version = "0.8.0", features = ["bitcoin", "derive"] }
bitcoin = "0.28.1"
miniscript_crate = { package = "miniscript", version = "7.0.0", optional = true }
bitcoin_hwi = { version = "0.2.0", optional = true }
electrum-client = { version = "0.10.1", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
serde_yaml = { version = "0.8.21", optional = true }
chrono = "0.4"
clap = { version = "~3.1.18", optional = true, features = ["derive"] }
bip39 = { version = "1.0.1", optional = true }
aes = { version = "0.7.5", optional = true }
rpassword = { version = "5.0.1", optional = true }
colored = { version = "2", optional = true }

[dev-dependencies]
bitcoin = { version = "0.28.1", features = ["rand"] }

[features]
default = []
all = ["keygen", "serde", "electrum", "hwi", "miniscript", "cli", "hot"]
hot = ["keygen", "bip39", "aes", "rpassword"]
hwi = ["bitcoin_hwi"]
miniscript = ["strict_encoding/miniscript", "miniscript_crate", "bitcoin_hd/miniscript", "bitcoin_onchain/miniscript", "descriptors/miniscript", "psbt/miniscript", "bitcoin_scripts/miniscript"]
cli = ["hwi", "miniscript", "serde", "colored", "clap", "serde_yaml", "bitcoin/base64"]
electrum = ["electrum-client", "bitcoin_onchain/electrum"]
keygen = ["bitcoin/rand", "amplify/rand", "descriptors/rand", "psbt/sign"]
serde = ["serde_crate", "serde_with", "amplify/serde",
         "bitcoin/use-serde", "bitcoin_scripts/serde", "bitcoin_hd/serde", "slip132/serde", "psbt/serde", "bitcoin_onchain/serde"]

[workspace]
members = [".", "slip132", "descriptors", "scripts", "hd", "psbt", "onchain"]
default-members = ["."]
exclude = ["dep_test", "libbitcoin"]
