[package]
name = "bp-wallet"
version = "0.9.0-alpha.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Bitcoin hierarchical deterministic derivation library"
readme = "../README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = []

[dependencies]
bitcoin_onchain = { path = "./onchain" }
bitcoin_hd = { path = "./hd" }
descriptors = { path = "./descriptors" }
psbt = { path = "./psbt" }
slip132 = { path = "./slip132" }

[features]
default = []
all = [
    "miniscript",
    "electrum",
    "strict_encoding",
    "serde",
]
miniscript = [
    "bitcoin_hd/miniscript",
#    "psbt/miniscript"
]
electrum = ["bitcoin_onchain/electrum"]
strict_encoding = ["slip132/strict_encoding"]
serde = [
    "slip132/serde",
    "bitcoin_onchain/serde",
    "bitcoin_hd/serde",
    "psbt/serde"
]

[workspace]
members = ["slip132", "hd", "psbt", "onchain"]
default-members = ["hd", "psbt", "onchain"]
