[package]
name = "bitcoin_hd"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin hierarchical deterministic wallet library"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/bitcoin_hd"
keywords = ["bitcoin", "wallet", "cryptocurrency", "cryptography", "bip32"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.8.2"
strict_encoding = "1.6.1"
bitcoin = "0.27.0"
miniscript = "6.0.1"
slip132 = { version = "0.5.0", path = "../slip132" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/serde", "miniscript/serde", "slip132/serde"]
