[package]
name = "slip132"
version = "0.3.0-rc.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin SLIP-132 standard implementation (parsing custom xpub/xpriv key formats)"
repository = "https://github.com/rust-bitcoin/descriptor-wallet"
homepage = "https://github.com/rust-bitcoin"
keywords = ["bitcoin", "wallet", "cryptocurrency", "cryptography", "bip32"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = []

[lib]
name = "slip132"
path = "src/lib.rs"
crate-type = ["dylib", "rlib", "staticlib"]

[dependencies]
amplify = { version = "3", features = ["stringly_conversions"] }
amplify_derive = "2.4.3"
strict_encoding = "1.0.0-rc.2" # TODO: Make strict encoding optional
bitcoin = { version = "0.26" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }

[features]
default = []
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]
