[package]
name = "bitcoin_onchain"
version = "0.8.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Bitcoin descriptors library (part of descriptor-wallet)"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/descriptors"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "bip32"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = []

[dependencies]
amplify = "3.12.1"
bitcoin = "0.28.1"
strict_encoding = "0.8.0"
descriptors = { version = "0.8.0", path = "../descriptors", default-features = false }
bitcoin_hd = { version = "0.8.0", path = "../hd" }
miniscript_crate = { package = "miniscript", version = "7.0.0", optional = true }
electrum-client = { version = "0.10.0", optional = true }
chrono = "0.4.19"

[features]
default = []
all = ["electrum", "miniscript"]
miniscript = ["miniscript_crate", "descriptors/miniscript", "bitcoin_hd/miniscript"]
electrum = ["electrum-client"]
