[package]
name = "psbt"
version = "0.6.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Partially signed bitcoin transaction v0-2 library (bip174, bip370, bip371)"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/psbt"
keywords = ["bitcoin", "wallet", "cryptocurrency", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.9.1"
bitcoin = "0.27.1"
descriptors = { version = "0.6.0", path = "../descriptors" }
bitcoin_scripts = { version = "0.6.0", path = "../scripts" }
bitcoin_hd = { version = "0.6.0", path = "../hd" }
miniscript = "6.0.1"
