[package]
name = "bitcoin_scripts"
version = "0.6.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin extended script types"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/scripts"
keywords = ["bitcoin", "wallet", "cryptocurrency", "cryptography", "bitcoin-script"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.9.1"
bitcoin = { version = "0.28", git = "https://github.com/LNP-BP/rust-bitcoin", branch = "taproot/all" }
miniscript = { version = "7", git = "https://github.com/LNP-BP/rust-miniscript", branch = "taproot" }
strict_encoding = { version = "1.8.0", git = "https://github.com/LNP-BP/client_side_validation", branch = "develop" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[dev-dependencies]
secp256k1 = { version = "0.20.3", features = ["global-context-less-secure"] }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde", "miniscript/serde"]
